# # Definitions of tags to detect
#
# ## General remarks
#
# - All length in meters
# - Ellipsis (...) signifies that the previous element can be repeated multiple times.
#
# ## Standalone tag definitions
# ### Remarks
#
# - name is optional
#
# ### Syntax
#
# standalone_tags:
#   [
#     {id: ID, size: SIZE, name: NAME},
#     ...
#   ]
standalone_tags:
  [
    {id: 10, size: 0.0464, name: target2},
    # {id: 1, size: 0.0464}
  ]
# ## Tag bundle definitions
# ### Remarks
#
# - name is optional
# - x, y, z have default values of 0 thus they are optional
# - qw has default value of 1 and qx, qy, qz have default values of 0 thus they are optional
#
# ### Syntax
#
# tag_bundles:
#   [
#     {
#       name: 'CUSTOM_BUNDLE_NAME',
#       layout:
#         [
#           {id: ID, size: SIZE, x: X_POS, y: Y_POS, z: Z_POS, qw: QUAT_W_VAL, qx: QUAT_X_VAL, qy: QUAT_Y_VAL, qz: QUAT_Z_VAL},
#           ...
#         ]
#     },
#     ...
#   ]

# from calibration

tag_bundles:
  [
   {
      name: 'origin2',
      layout:
        [
          {id: 0, size: 0.0464, x: 0.0000, y: 0.0000, z: 0.0000, qw: 1.0000, qx: 0.0000, qy: 0.0000, qz: 0.0000},
          {id: 1, size: 0.0464, x: 0.0402, y: -0.2637, z: 0.0247, qw: 0.9999, qx: 0.0099, qy: -0.0082, qz: 0.0053}
        ]
    },
    {
        name: 'object2',
        layout:
        [
          {id: 7,  size: 0.04775, x: 0.0000, y: 0.0000, z: 0.0000, qw: 1.0000, qx: 0.0000, qy: 0.0000, qz: 0.0000},
          {id: 11, size: 0.04775, x: 0.0302, y: -0.0004, z: -0.0335, qw: 0.7113, qx: -0.0002, qy: 0.7028, qz: -0.0032},
          {id: 8,  size: 0.04775, x: -0.0008, y: 0.0296, z: -0.0335, qw: 0.7062, qx: -0.7079, qy: 0.0055, qz: -0.0123},
          {id: 9,  size: 0.04775, x: -0.0017, y: -0.0311, z: -0.0332, qw: 0.7044, qx: 0.7098, qy: 0.0004, qz: -0.0000},
          {id: 6,  size: 0.04775, x: -0.0337, y: -0.0018, z: -0.0310, qw: 0.4922, qx: 0.4886, qy: -0.5155, qz: -0.5033}
        ]

    }
  ]
