# # Definitions of tags to detect
#
# ## General remarks
#
# - All length in meters
# - Ellipsis (...) signifies that the previous element can be repeated multiple times.
#
# ## Standalone tag definitions
# ### Remarks
#
# - name is optional
#
# ### Syntax
#
# standalone_tags:
#   [
#     {id: ID, size: SIZE, name: NAME},
#     ...
#   ]
standalone_tags:
  [
    {id: 6, size: 0.04775},
    {id: 7, size: 0.04775},
    {id: 8, size: 0.04775},
    {id: 9, size: 0.04775},
    {id: 11, size: 0.04775},
  ]

# from calibration

tag_bundles:
  [
  ]
