# # Definitions of tags to detect
#
# ## General remarks
#
# - All length in meters
# - Ellipsis (...) signifies that the previous element can be repeated multiple times.
#
# ## Standalone tag definitions
# ### Remarks
#
# - name is optional
#
# ### Syntax
#
# standalone_tags:
#   [
#     {id: ID, size: SIZE, name: NAME},
#     ...
#   ]
standalone_tags:
  [
    # {id: 0, size: 0.0464},
    # {id: 1, size: 0.0464}
  ]
# ## Tag bundle definitions
# ### Remarks
#
# - name is optional
# - x, y, z have default values of 0 thus they are optional
# - qw has default value of 1 and qx, qy, qz have default values of 0 thus they are optional
#
# ### Syntax
#
# tag_bundles:
#   [
#     {
#       name: 'CUSTOM_BUNDLE_NAME',
#       layout:
#         [
#           {id: ID, size: SIZE, x: X_POS, y: Y_POS, z: Z_POS, qw: QUAT_W_VAL, qx: QUAT_X_VAL, qy: QUAT_Y_VAL, qz: QUAT_Z_VAL},
#           ...
#         ]
#     },
#     ...
#   ]

# from calibration

tag_bundles:
  [
   {
      name: 'origin',
      layout:
        [
          {id: 0, size: 0.05, x: 0.0000, y: 0.0000, z: 0.0000, qw: 1.0000, qx: 0.0000, qy: 0.0000, qz: 0.0000},
          {id: 1, size: 0.05, x: 0.0402, y: -0.2637, z: 0.0247, qw: 0.9999, qx: 0.0099, qy: -0.0082, qz: 0.0053}
        ]
    },
    {
      name: 'object',
      layout:
        [
          {id: 6, size: 0.05, x: 0.0000, y: 0.0000, z: 0.0000, qw: 1.0000, qx: 0.0000, qy: 0.0000, qz: 0.0000},
          {id: 9, size: 0.05, x: -0.0615, y: 0.0002, z: -0.0567, qw: 0.0055, qx: -0.7085, qy: -0.0154, qz: 0.7055},
          {id: 8, size: 0.05, x: 0.0045, y: -0.0539, z: -0.0610, qw: 0.4933, qx: 0.4965, qy: 0.5159, qz: -0.4939},
          {id: 11, size: 0.05, x: -0.0008, y: 0.0567, z: -0.0566, qw: 0.7149, qx: -0.6992, qy: -0.0040, qz: 0.0054},
          {id: 7, size: 0.05, x: 0.0613, y: 0.0008, z: -0.0547, qw: 0.0052, qx: -0.7081, qy: 0.0131, qz: -0.7060}
        ]
    }
  ]
